# Generated by Django 3.0.2 on 2020-01-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('northwind', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
